# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [9]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [10]:
A = np.arange(1, 16).reshape(3,5)

In [11]:
print(A.shape)
print(A.size)
print(A.dtype)
print(A.ndim)

(3, 5)
15
int64
2


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [12]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [13]:
print(str(C*2) + "\n\n" + str(B*2))
print(B+C) # båda måste vara i samma shape eller att den ena är en skalär (aka ett enda värde)
print(B-C) # båda måste vara i samma shape eller att den ena är en skalär (aka ett enda värde)
print(B*C) # båda måste vara i samma shape eller att den ena är en skalär (aka ett enda värde)
# Matrismulitplikation
# A[0][0] multipliceras med B[0][0]
# A[0][1] multipliceras med B[1][0]
print(B@C) # Antalet kolumner i A måste vara detsamma som antalet rader i B
# AB = [antalet rader i A][antalet kolumner i B]


[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [14]:
B = np.arange(1, 10).reshape(3, 3)
print("print B")
print(B)

print("exponatiated each number")
print(B**2)

print("check for the lowest value element overall")
print(B.min())

print("lowest in each row")
for row in B:
    print(f'out of these {row} ' + str(row.min()) + " is the lowest")
# or:
B.min(axis=0)

print("lowest value in each column")
# .T is transpose fill each element in the list(=row) in a new list(=row). First row is instead first column
for row in B.T:
    print(min(row))
# or
print(B.min(axis=0))
# or
print(B.T.min(axis=1))

print("Find the index value for the minimum value in the whole matrix ")
# (hint: use np.argmin).
print(B.argmin())

print("Find the index value for the minimum value in each row ")
# (hint: use np.argmin).
print(B.argmin(axis=1))

print("Calculate the sum for all elements")
print(B.sum())

print("Calculate the mean for each column.")
print(B.mean(axis=0))

print("Calculate the median for each column.")
print(np.median(B, axis=0))

print B
[[1 2 3]
 [4 5 6]
 [7 8 9]]
exponatiated each number
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
check for the lowest value element overall
1
lowest in each row
out of these [1 2 3] 1 is the lowest
out of these [4 5 6] 4 is the lowest
out of these [7 8 9] 7 is the lowest
lowest value in each column
1
2
3
[1 2 3]
[1 2 3]
Find the index value for the minimum value in the whole matrix 
0
Find the index value for the minimum value in each row 
[0 0 0]
Calculate the sum for all elements
45
Calculate the mean for each column.
[4. 5. 6.]
Calculate the median for each column.
[4. 5. 6.]


In [15]:
# List comprehension
# ger alltid en lista
print(f'Dessa nuffror fick vi fram: {[elem for row in B for elem in row if elem > 5]}')
# därför gör jag en join
print(f'Dessa nuffror fick vi fram: {"|".join([str(elem) for row in B for elem in row if elem > 5])}')

Dessa nuffror fick vi fram: [np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
Dessa nuffror fick vi fram: 6|7|8|9


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [16]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

only the mentioned dimensions are shown

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [18]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [20]:
print(A[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [21]:
a = np.arange(30)
b = np.reshape(a, shape=(2, 3, -1)) # -1 is "calculate missing value" 
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### Lines:
1. a is declared as a list of 30 integers is created
2. b is declared as a reshape of a in 2 rows and 3 columns and a z axis with an arbituary value, calculated by NumPy. The third axis is also the thrid dimension.
3. a is printed, as we can see all of it is in the same row
4. an empty row is printed
5. 
6. b is printed and we can clearly see it is three dimensional. I think it is easier to let all new dimensions and arrays have their own row, as demonstrated below:
```
[ # first dimension
    [ # second dimension
        [ 0  1  2  3  4] # third dimension
        [ 5  6  7  8  9] # 3rd
        [10 11 12 13 14]# 3rd
    ], # 2nd
    [ # 2nd
        [15 16 17 18 19] # 3rd
        [20 21 22 23 24] # 3rd
        [25 26 27 28 29] # 3rd
    ] # 2nd
] # 1st
```



# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [22]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
if m1.shape == m2.shape:
    print(m1 + m2)
else:
    print("not the same shape")

not the same shape


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [23]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [24]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [80]:
initial = np.arange(1, 7)
m1 = initial.reshape(2, 3)
m2 = initial.reshape(3, 2)


def add_mult_matrices(matrice_1, matrice_2, /, method):
    if not isinstance(matrice_1, np.ndarray) or not isinstance(matrice_2, np.ndarray):
        print(f"Wrong datatype of matrices. Should be numpy.ndarray")
        print(f"matrice_1 is {type(matrice_1)}")
        print(f"matrice_1 is {type(matrice_2)}")
    else:
        match method:
            case 'add':
                if matrice_1.shape != matrice_2.shape:
                    print(
                        f'matrice_1 and matrice_2 need to have the same shape for matrix addition')
                    print(f'matrice_1 is of shape {matrice_1.shape}')
                    print(f'matrice_2 is of shape {matrice_2.shape}')
                else:
                    print(f'everything has worked out, here\'s your matrice addition: \n {
                        matrice_1 + matrice_2}')
            case 'multiply':
                # in this case we can ONLY compare 2d ndarrays with the shape of at least (2,2).
                # To make 3d+ possible I would have to write another if-statement for each dimension
                if matrice_1.shape[1] != matrice_2.shape[0]:
                    print(
                        'matrice_1 has to have equal amount of columns as matrice_2 has rows!')
                    print(f'matrice_1 has {matrice_1.shape[1]} columns and matrice_2 has {
                        matrice_2.shape[0]} rows')
                else:
                    print(f'everything has worked out, here\'s your matrice multiplication: \n {
                        matrice_1@matrice_2}')
            case _:
                print("Kwarg method must be either 'add' or 'multiply'")
                print(f'method says {method}')


test_runs = [
    (m1, m1, 'add'),
    (m1, m2, 'multiply'),
    (m1, m2, 'add'),
    (m1, m1, 'multiply'),
    (m1, m1, 'touchdwn!')
]

for run in test_runs:
    add_mult_matrices(*run)
    print('\n')

# add_mult_matrices(m1, m1, method='add')
# add_mult_matrices(m1, m2, method='multiply')
# add_mult_matrices(m1, m2, method='add')
# add_mult_matrices(m1, m1, method='multiply')
# add_mult_matrices(m1, m1, method='touchdown!')

everything has worked out, here's your matrice addition: 
 [[ 2  4  6]
 [ 8 10 12]]


everything has worked out, here's your matrice multiplication: 
 [[22 28]
 [49 64]]


matrice_1 and matrice_2 need to have the same shape for matrix addition
matrice_1 is of shape (2, 3)
matrice_2 is of shape (3, 2)


matrice_1 has to have equal amount of columns as matrice_2 has rows!
matrice_1 has 3 columns and matrice_2 has 2 rows


Kwarg method must be either 'add' or 'multiply'
method says touchdwn!




### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [61]:
# Uppgifterna 10.1.1

y = np.array([4,3]) # en matematisk vektor i Numpy representeras alltid av en array
print(y.shape)
x = y.reshape(1,2) # pga differensen mellan matteboken och numpy
print(x)

print("a")
print(x.shape)

print("b")
print(5 * x)

print("c")
print(3 * x)

print("d")
print((5 * x) + (3 * x))

print("e")
print(8 * x)

print("f")
print((4 * x) - x)

print("g")
print(x.T)
print(x.T.shape)

print("h")
print("x.T + x är inte definierat men fungerar i Numpy")
print(x.T + x)

print("i")
x_norm = np.linalg.norm(x)
print(x_norm)

(2,)
[[4 3]]
a
(1, 2)
b
[[20 15]]
c
[[12  9]]
d
[[32 24]]
e
[[32 24]]
f
[[12  9]]
g
[[4]
 [3]]
(2, 1)
h
x.T + x är inte definierat men fungerar i Numpy
[[8 7]
 [7 6]]
i
5.0


In [68]:
# Uppgifterna 10.1.2

vector = [
    [3],
    [7],
    [0],
    [11]
]

v = np.array(vector) # because Numpy...

print("a")
print(v.shape)

print("b")
print((2*v))

print("c")
print((5*v) + (2*v))

print("d")
print((4*v) - (2*v))

print("e")
print(v.T)

v_norm = np.linalg.norm(v)
print(v_norm)

a
(4, 1)
b
[[ 6]
 [14]
 [ 0]
 [22]]
c
[[21]
 [49]
 [ 0]
 [77]]
d
[[ 6]
 [14]
 [ 0]
 [22]]
e
[[ 3  7  0 11]]
13.379088160259652


In [73]:
# Uppgifterna 10.1.3
vector_1 = [4,3,1,5]
vector_2 = [2,3,1,1]

vector_1 = np.array(vector_1)
vector_2 = np.array(vector_2)
print(str(vector_1.shape) + "\n")

print("a")
vector_1_norm = np.linalg.norm(vector_1)
print(vector_1_norm)

print("b")
vector_1_minus_vector_2_norm = np.linalg.norm((vector_1 - vector_2))
print(vector_1_minus_vector_2_norm)

(4,)

a
7.14142842854285
b
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [82]:
# Uppgifterna 10.2.1
A = [
    [2, 1, -1],
    [1, -1, 1]
]

B = [
    [4, -2, 1],
    [2, -4, -2]
]

C = [
    [1, 2],
    [2, 1]
]

D = [
    [3, 4],
    [4, 3]
]

E = [
    [1],
    [2]
]

I = [
    [1, 0],
    [0, 1]
]

A = np.array(A)
B = np.array(B)
C = np.array(C)
D = np.array(D)
E = np.array(E)
I = np.array(I)

print(A.shape)
print(B.shape)
print(C.shape)
print(D.shape)
print(E.shape)
print(I.shape)


(2, 3)
(2, 3)
(2, 2)
(2, 2)
(2, 1)
(2, 2)


In [98]:
# 10.2.1 forts...
print('a )')
print(2*A)

print('b )')
print(B-2*A)

print('c )')
print('"3C - 2E" är ej definierat')

print('d )')
print(2*D - 3*C)

print('e )')
print(D.T + 2*D)

print('f )')
print(2*C.T - 2*D.T)

print('g )')
print('"A.T - B" är ej definierat')


print('h )')
print('"AC" är ej definierat')

print('i )')
print(C@D)

print('j )')
print(C@B)

print('k )')
print(C@I)

print('l )')
print(A@B.T)

a )
[[ 4  2 -2]
 [ 2 -2  2]]
b )
[[ 0 -4  3]
 [ 0 -2 -4]]
c )
"3C - 2E" är ej definierat
d )
[[3 2]
 [2 3]]
e )
[[ 9 12]
 [12  9]]
f )
[[-4 -4]
 [-4 -4]]
g )
"A.T - B" är ej definierat
h )
"AC" är ej definierat
i )
[[11 10]
 [10 11]]
j )
[[  8 -10  -3]
 [ 10  -8   0]]
k )
[[1 2]
 [2 1]]
l )
[[5 2]
 [7 4]]


In [99]:
# Uppgift 10.2.2
A = [
    [2, 3, 4],
    [5, 4, 1]
]
A = np.array(A)
print(A@A.T)

[[29 26]
 [26 42]]


In [109]:
# Uppgift 10.2.3
A = [
    [1, 2],
    [2, 4]
]
B = [
    [2, 1],
    [1, 3]
]
C = [
    [4, 3],
    [0, 2]
]
A = np.array(A)
B = np.array(B)
C = np.array(C)

print(A@B)
print(A@C)

# as per this StackOverflow suggestion with 669 points:
# https://stackoverflow.com/questions/10580676/comparing-two-numpy-arrays-for-equality-element-wise
print(np.array_equal((A@B),(A@C)))
print(np.array_equal((B),(C)))

True
False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [16]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [17]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [18]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
