# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(A.shape)
print(A.size)
print(A.dtype)
print(A.ndim)

(3, 5)
15
int64
2


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(str(C*2) + "\n\n" + str(B*2))
print(B+C) # båda måste vara i samma shape eller att den ena är en skalär (aka ett enda värde)
print(B-C) # båda måste vara i samma shape eller att den ena är en skalär (aka ett enda värde)
print(B*C) # båda måste vara i samma shape eller att den ena är en skalär (aka ett enda värde)
# Matrismulitplikation
# A[0][0] multipliceras med B[0][0]
# A[0][1] multipliceras med B[1][0]
print(B@C) # Antalet kolumner i A måste vara detsamma som antalet rader i B
# AB = [antalet rader i A][antalet kolumner i B]


[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [25]:
B = np.arange(1, 10).reshape(3, 3)
print("print B")
print(B)

print("exponatiated each number")
print(B**2)

print("check for the lowest value element overall")
print(B.min())

print("lowest in each row")
for row in B:
    print(f'out of these {row} ' + str(row.min()) + " is the lowest")
# or:
B.min(axis=0)

print("lowest value in each column")
# .T is transpose fill each element in the list(=row) in a new list(=row). First row is instead first column
for row in B.T:
    print(min(row))
# or
print(B.min(axis=0))
# or
print(B.T.min(axis=1))

print("Find the index value for the minimum value in the whole matrix ")
# (hint: use np.argmin).
print(B.argmin())

print("Find the index value for the minimum value in each row ")
# (hint: use np.argmin).
print(B.argmin(axis=1))

print("Calculate the sum for all elements")
print(B.sum())

print("Calculate the mean for each column.")
print(B.mean(axis=0))

print("Calculate the median for each column.")
print(np.median(B, axis=0))

print B
[[1 2 3]
 [4 5 6]
 [7 8 9]]
exponatiated each number
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
check for the lowest value element overall
1
lowest in each row
out of these [1 2 3] 1 is the lowest
out of these [4 5 6] 4 is the lowest
out of these [7 8 9] 7 is the lowest
lowest value in each column
1
2
3
[1 2 3]
[1 2 3]
Find the index value for the minimum value in the whole matrix 
0
Find the index value for the minimum value in each row 
[0 0 0]
Calculate the sum for all elements
45
Calculate the mean for each column.
[4. 5. 6.]
Calculate the median for each column.
[4. 5. 6.]


In [9]:
# List comprehension
# ger alltid en lista
print(f'Dessa nuffror fick vi fram: {[elem for row in B for elem in row if elem > 5]}')
# därför gör jag en join
print(f'Dessa nuffror fick vi fram: {"|".join([str(elem) for row in B for elem in row if elem > 5])}')

Dessa nuffror fick vi fram: [np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
Dessa nuffror fick vi fram: 6|7|8|9


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [26]:
A[1]

np.int64(6)

**Answer:**

only the mentioned dimensions are shown

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
print(A[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [34]:
a = np.arange(30)
b = np.reshape(a, shape=(2, 3, -1)) # -1 is "calculate missing value" 
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a is declared as a list of 30 integers is created
b is declared as a reshape of a in 


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [36]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
if m1.shape == m2.shape:
    print(m1 + m2)
else:
    print("not the same shape")

not the same shape


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [14]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [15]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [45]:
x = np.array([4,3])

x.shape
print(x)

# a


[4 3]


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [16]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [17]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [18]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
